spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: default
  sql:
    init:
      mode: never
      platform: sqlite
management:
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
    db:
      enabled: true
logging:
  level:
    root: INFO
cds:
  data-source:
    auto-config:
      enabled: false
concur:
  oauth:
    token-url: https://eu2.api.concursolutions.com/oauth2/v0/token
    client-id: ${CONCUR_CLIENT_ID}
    client-secret: ${CONCUR_CLIENT_SECRET}
    init_refresh_token: ${CONCUR_REFRESH_TOKEN}
  user:
    api-url: https://eu2.api.concursolutions.com/profile/identity/v4/Users

