### Create Product

POST https://localhost:8080/odata/v4/AdminService/Products
// remember to turn into http for local testing
Content-Type: application/json
Authorization: Basic cHJpdmlsZWdlZDo=

{"ID": 45, "title": "My Tutorial Product", "descr": "You are doing an awesome job!"}

### Read Product
GET https://localhost:8080/odata/v4/AdminService/Products
// remember to turn into http for local testing
Authorization: Basic cHJpdmlsZWdlZDo=