### Create Product

POST https://supreme-space-waffle-4qgjwp6wwgphjgw4-8080.app.github.dev/odata/v4/AdminService/Products
Content-Type: application/json
Authorization: Basic cHJpdmlsZWdlZDo=

{"ID": 45, "title": "My Tutorial Product", "descr": "You are doing an awesome job!"}

### Read Product
GET https://supreme-space-waffle-4qgjwp6wwgphjgw4-8080.app.github.dev/odata/v4/AdminService/Products
Authorization: Basic cHJpdmlsZWdlZDo=